#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --remove mpirun /usr/bin/mpirun.openmpi
    update-alternatives --remove mpi /usr/bin/mpicc.openmpi
    update-alternatives --remove mpi-include /usr/libexec/openmpi/include
fi
