all:
	install -d $(dstroot)/usr/libexec/awk/bin
	install -m755 $(srcroot)/a.out $(dstroot)/usr/libexec/awk/bin/awk
	install -d $(dstroot)/usr/libexec/awk/man/man1
	install -m444 $(srcroot)/awk.1 $(dstroot)/usr/libexec/awk/man/man1/awk.1
