all:
	sed -i -e "s/FATAL_ERROR/STATUS/g" $(dstroot)/usr/lib/openjpeg-2.5/OpenJPEGTargets*.cmake
	ln -s openjpeg-2.5 $(dstroot)/usr/include/openjpeg-2.1
	ln -s openjpeg-2.5 $(dstroot)/usr/lib/openjpeg-2.1
