#!/bin/sh -e

case "$1" in
    configure)
        update-alternatives \
            --install /usr/bin/lua lua-interpreter /usr/bin/lua5.2 19 \
            --slave /usr/share/man/man1/lua.1 lua-manual \
                /usr/share/man/man1/lua5.2.1
        update-alternatives \
            --install /usr/bin/luac lua-compiler /usr/bin/luac5.2 19 \
            --slave /usr/share/man/man1/luac.1 lua-compiler-manual \
                /usr/share/man/man1/luac5.2.1
        ;;
esac
